from .config import (
    PROJECT_ROOT,
    DATA_DIR,

    TEXT_DATA_DIR,
    TEXT_DATASET_PATH,
    SYNONYMS_PATH,

    IMG_DATA_DIR,
    METADATA_PATH,
    TRAIN_IMG_DIR,
    TEST_IMG_DIR,

    ARTIFACTS_DIR,
    NER_MODEL_DIR,
    RESNET_MODEL_DIR,
    RESNET_CLASSES_FILE,
    RESNET_CLASSES_DIR,
)
